### ISSUE TITLE
Display the time the data was last scraped from the mensa website

### ISSUE THREAD

**Issue by Draculente** [Importantus/speiseplan-tray#4]
The API now supports to get the time its data was last updated.

https://speiseplan.mcloud.digital/meals/last-update returns the data in UTC time.

When fetching the data it is important to first fetch the data and the last update date after that, because the data fetch will update the cache.

**Comment by Importantus** [comment]
I don't plan to include it in the near future but I do try to keep it in mind for when I have a bit more time  again.
