### ISSUE TITLE
Fix tray icon diplay on macOS

### ISSUE THREAD

**Issue by hoppjan** [Importantus/speiseplan-tray#9]
- the resolution does not match my high-res display and
- the icon size does not match the other icons, which have a bit more padding

<img width="300" alt="Screenshot showing the previously described issues" src="https://github.com/Importantus/speiseplan-tray/assets/83405332/d682dd8f-abb1-40d5-9c85-d771b3e181bc">

As you can see, it looks out of place next to the other icons.

**Comment by Importantus** [comment]
You're right. For MacOs you need template files: https://www.electronjs.org/docs/latest/api/native-image#template-image

I have no idea how to make better ones but I'll look into it. Of course, you'd have to test it. ^^

**Comment by Importantus** [comment]
Found this article stating to best use 8/11 of the available space for the actual icon: https://bjango.com/articles/designingmenubarextras/ 

And template files are just pngs that use only the alpha channel.
